version: '3.7'
services:
 jenkins:
  build:
   context: .
   dockerfile: ./jenkins.Dockerfile
  volumes:
   - ./jenkins_home:/var/jenkins_home
   - .:/app
  ports:
   - 8081:8080
  user: root
 aws:
  image: organs/awscli
  environment:
   AWS_ACCESS_KEY_ID: secretID
   AWS_SECRET_ACCESS_KEY: secretAK
   AWS_REGION: eu-central-1
   AWS_DEFAULT_REGION: eu-central-1
  volumes:
   - .:/app
  working_dir: /app
 terraform:
  build:
   context: .
   dockerfile: terraform.Dockerfile
  environment:
   AWS_ACCESS_KEY_ID: secretID
   AWS_SECRET_ACCESS_KEY: secretAK
   AWS_REGION: eu-central-1
   AWS_DEFAULT_REGION: eu-central-1
  volumes:
   - .:/app
  working_dir: /app
 selenium: 
  image: selenium/standalone-chrome-debug
  ports:
   - 4444:4444
   - 5901:5900
 website:
  image: nginx:alpine
  volumes:
   - ./website:/website
   - ./nginx.conf:/etc/nginx/nginx.conf
  build:
   context: .
  ports:
   - 80:80
 unit-tests:
  environment:
   SELENIUM_HOST: selenium
   SELENIUM_PORT: 4444
  build:
   dockerfile: rspec.dockerfile
   context: .
  volumes:
   - .:/app
  command:
   - --pattern
   - /app/spec/unit/*_spec.rb
 integration-tests:
  environment:
   SELENIUM_HOST: selenium
   SELENIUM_PORT: 4444
   WEBSITE_URL: http://doesnot.exist
  build:
   dockerfile: rspec.dockerfile
   context: .
  volumes:
   - .:/app
  entrypoint: rspec
  command:
   - --pattern
   - /app/spec/integration/*_spec.rb

