version: '3.7'
services:
 terraform:
  build:
   context: .
   dockerfile: terraform.Dockerfile
  volumes:
   - .:/app
  working_dir: /app
 selenium: 
  image: selenium/standalone-chrome-debug
  ports:
   - 4444:4444
   - 5901:5900
 website:
  build:
   context: .
  ports:
   - 80:80
 unit-tests:
  environment:
   SELENIUM_HOST: selenium
   SELENIUM_PORT: 4444
  build:
   dockerfile: rspec.dockerfile
   context: .
  volumes:
   - .:/app
  command:
   - --pattern
   - /app/spec/unit/*_spec.rb
